Treat all Python environments as externally-managed

diff --git a/setup.d/0100-pip b/setup.d/0100-pip
--- a/setup.d/0100-pip
+++ b/setup.d/0100-pip
@@ -5,38 +5,26 @@ function have_command {
     command -V "$1" >/dev/null 2>&1
 }
 
-extmanaged="$(python3 "$(dirname "$0")"/../util/externally-managed.py)"
-
-if [ "$extmanaged" = yes ]
-then
-    while read -r cmd pkg require
-    do
-        if ! have_command "$cmd"
+while read -r cmd pkg require
+do
+    if ! have_command "$cmd"
+    then
+        if have_command brew
+        then brew install "$pkg"
+        elif have_command apt-get && sudo -n true 2>/dev/null
+        then sudo apt-get install -y "$pkg"
+        elif [ "$require" = yes ]
         then
-            if have_command brew
-            then brew install "$pkg"
-            elif have_command apt-get && sudo -n true 2>/dev/null
-            then sudo apt-get install -y "$pkg"
-            elif [ "$require" = yes ]
-            then
-                printf '\x1B[31m[ERROR] Python environment is externally managed, and %s is not installed.\x1B[m\n' "$cmd" >&2
-                exit 1
-            else
-                printf '\x1B[33m[WARNING] Python environment is externally managed, and %s is not installed.\x1B[m\n' "$cmd" >&2
-            fi
+            printf '\x1B[31m[ERROR] %s is not installed.\x1B[m\n' "$cmd" >&2
+            exit 1
+        else
+            printf '\x1B[33m[WARNING] %s is not installed.\x1B[m\n' "$cmd" >&2
         fi
-    done <<EOT
+    fi
+done <<EOT
 pipx pipx yes
 virtualenvwrapper.sh virtualenvwrapper no
 EOT
-else
-    if ! have_command pip3
-    then wget -O- https://bootstrap.pypa.io/get-pip.py | python3 - --user
-    fi
-
-    python3 -m pip install --user --upgrade pip
-    python3 -m pip install --user --upgrade pipx virtualenvwrapper
-fi
 
 pipx install black
 pipx install build
